// react-demo/src/query-list/QueryList.js
import React from 'react';
import Query from './Query.js'
import List from './List.js'
import axios from 'axios'

class QueryList extends React.Component{
  constructor(props){
      super(props)
      this.state={ 
        list:[]
      }
  }
  componentDidMount(){
    this.getList()
  }
  async getList(id=-1){
    const res=await axios.request({
      method:'get',
      url:'http://111.229.14.189/gk-api/util/list',
      params:{
        id:id
      }
    })
    this.setState({list:res.data})
  }
  handleQuery=(value)=>{
   this.getList(value)
  }
  render(){
    return (
      <div className="query-list" >
        <Query onQuery={this.handleQuery}></Query>
        <List list={this.state.list}></List>
      </div>
    );  
  }

}


export default QueryList;

// vue-demo/src/query-list/query-list.vue
<template>
    <section>
        <!-- 查询列表组件  查询框    列表 -->
        <query @on-change="handleChange"></query>
        <list :list="list"></list>
    </section>
</template>

<script>
import query from './query'
import list from './list'
import axios from 'axios'

export default {
    name: 'query-list',
    components: {
        query,
        list,
    },
    data() {
        return {
            list: [],
        }
    },
    methods: {
        async getList(id = -1) {
            const res = await axios.request({
                method: 'get',
                url: 'http://111.229.14.189/gk-api/util/list',
                params: {
                    id: id,
                },
            })
            this.list = res.data
        },
        handleChange(id) {
            this.getList(id)
        },
    },
    created() {
        this.getList()
    },
}
</script>

<style lang="less" scoped></style>
